const TATTOO_CATEGORIES = [
  "Anime",
  "Realism",
  "Micro Realism",
  "Portrait",
  "Black & Grey",
  "Fine Line",
  "Minimalist",
  "Traditional",
  "Neo Traditional",
  "Japanese / Irezumi",
  "Tribal",
  "Geometric",
  "Mandala",
  "Dotwork",
  "Blackwork",
  "Watercolor",
  "Lettering / Script",
  "Ornamental",
  "Abstract",
  "Sketch",
  "Biomechanical",
  "Chicano",
  "Color Tattoo",
  "Religious / Spiritual",
  "Cover Up",
  "Custom Design",
];

module.exports = TATTOO_CATEGORIES;